version: "3.8"
services:
  polkadot:
    container_name: polkadot
    image: lanmeng656/cess-data-store-sidecar:latest
    volumes:
      - ~/polkadot-data:/data
    # ports:
    #   - "9944:9944"
    command: '--chain polkadot --unsafe-ws-external --rpc-cors=all'

  sidecar:
    # build: .
    image: docker.io/parity/substrate-api-sidecar:latest
    read_only: true
    ports:
      - "8080:8080"
    environment:
      SAS_SUBSTRATE_WS_URL: ws://polkadot:9944
